### ISSUE TITLE
May you post a example of a config.yml

### ISSUE THREAD

**Issue by holzhannes** [targodan/maildav#1]
I found your tool and I like to test and use it, but I am struggling to get i running. At the moment I have problems to set up a right timeout. I am using a config.yml like this one:

```
sources:
    - name: E-Mail
    - server: IMAP-Server
    - port: 993
    - tls: true
    - username: USERNAME
    - password: PW
destinations:
    - name: Nextcloud
    - baseURL: https://example.com/remote.php/webdav/
    - username: USERNAME
    - password: PW
pollers:
    - source: E-Mail
    - destination: Nextcloud
    - timeout: 6000
```
